### ISSUE TITLE
Feedback on package_info

### ISSUE THREAD

**Issue by memsharded** [spektrof/conan_contribute#1]
Some quick feedback on:

```python
def package_info(self):
    self.cpp_info.name = "pkg_b"
    self.cpp_info.components["pkg_b_lib"].name = "pkg_b_lib"
    self.cpp_info.components["pkg_b_lib"].includes = ["include"]
    self.cpp_info.components["pkg_b_lib"].requires = ["pkg_a::pkg_a_lib"]
```

- ``cpp_info.name`` shouldn't be defined. The way that consumers will receive information of dependencies is via ``self.dependencies["pkg_b"].ref`` (that is the full reference, including revision, name can be ``self.dependencies["pkg_b"].ref.name``.
- It is not necessary, and not even recommended to use components if you only have 1 library/artifact inside the package. Even for cases where there are more than 1 library, but they are used together, it is not necessary nor recommmended to define components.
- ``self.cpp_info.components["pkg_b_lib"].includes`` seems to be wrong, but ``includedirs`` should be used.
- ``self.cpp_info.components["pkg_b_lib"].name`` defining the ``name`` of a component shouldn't be done this way. This was kind of necessary in the past for open source packages in ConanCenter to match some conventions, but is already legacy and deprecated.

**Comment by spektrof** [comment]
Hi @memsharded ,

Thank you for checking and your feedback.

I just did a quick adjustments in the PR.

**Comment by spektrof** [comment]
I close this issue as the PR has been merged.

Thank you @memsharded for checking!
